kind: Secret
apiVersion: v1
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4= 
  password: MWYyZDFlMmU2N2Rm
---
kind: Pod
apiVersion: v1
metadata:
  name: secret-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
  - name: my-test-container
    image: k8s.gcr.io/busybox
    command:
    - ls
    - "-alR"
    - "/etc/secrets"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secrets"
---
kind: Pod
apiVersion: v1
metadata:
  name: secret-pod-256
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
      defaultMode: 256
  containers:
  - name: my-test-container-256
    image: k8s.gcr.io/busybox
    command:
    - ls
    - "-alR"
    - "/etc/secrets"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secrets"
---
kind: Pod
apiVersion: v1
metadata:
  name: secret-pod-511
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
      defaultMode: 511
  containers:
  - name: my-test-container-511
    image: k8s.gcr.io/busybox
    command:
    - ls
    - "-alR"
    - "/etc/secrets"
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secrets"
